// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-rLOGTfehDY39TgYQS53E640qHkrrs0U',
    appId: '1:577036105364:web:4d125aa0d339b2154ba681',
    messagingSenderId: '577036105364',
    projectId: 'minimal-social-app-f0c27',
    authDomain: 'minimal-social-app-f0c27.firebaseapp.com',
    storageBucket: 'minimal-social-app-f0c27.appspot.com',
    measurementId: 'G-6K6ESVH4ML',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3RTVlSDonMjTAcORJ1CjMpznGnQsQKw0',
    appId: '1:577036105364:android:55153e88d44b7f784ba681',
    messagingSenderId: '577036105364',
    projectId: 'minimal-social-app-f0c27',
    storageBucket: 'minimal-social-app-f0c27.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8PLoCnFLt4_fhEvrkEd6xY9hbGITMSmQ',
    appId: '1:577036105364:ios:49f5e727bf02fa884ba681',
    messagingSenderId: '577036105364',
    projectId: 'minimal-social-app-f0c27',
    storageBucket: 'minimal-social-app-f0c27.appspot.com',
    iosBundleId: 'com.example.minimalSocialMedia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8PLoCnFLt4_fhEvrkEd6xY9hbGITMSmQ',
    appId: '1:577036105364:ios:49f5e727bf02fa884ba681',
    messagingSenderId: '577036105364',
    projectId: 'minimal-social-app-f0c27',
    storageBucket: 'minimal-social-app-f0c27.appspot.com',
    iosBundleId: 'com.example.minimalSocialMedia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-rLOGTfehDY39TgYQS53E640qHkrrs0U',
    appId: '1:577036105364:web:b26efca6490c5ec54ba681',
    messagingSenderId: '577036105364',
    projectId: 'minimal-social-app-f0c27',
    authDomain: 'minimal-social-app-f0c27.firebaseapp.com',
    storageBucket: 'minimal-social-app-f0c27.appspot.com',
    measurementId: 'G-CEN8QR2X6E',
  );
}
